package com.advertisement.entity;
// Generated Apr 26, 2017 12:47:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="advertise"
)
public class Admin  implements java.io.Serializable {


     private Integer adminId;
     private String adminName;
     private String adminEmail;
     private String adminPassword;
     private byte[] adminPhoto;

    public Admin() {
    }

	
    public Admin(String adminName, String adminEmail, String adminPassword) {
        this.adminName = adminName;
        this.adminEmail = adminEmail;
        this.adminPassword = adminPassword;
    }
    public Admin(String adminName, String adminEmail, String adminPassword, byte[] adminPhoto) {
       this.adminName = adminName;
       this.adminEmail = adminEmail;
       this.adminPassword = adminPassword;
       this.adminPhoto = adminPhoto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="admin_id", unique=true, nullable=false)
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    
    @Column(name="admin_name", nullable=false, length=200)
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    
    @Column(name="admin_email", nullable=false, length=100)
    public String getAdminEmail() {
        return this.adminEmail;
    }
    
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }

    
    @Column(name="admin_password", nullable=false, length=100)
    public String getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }

    
    @Column(name="admin_photo")
    public byte[] getAdminPhoto() {
        return this.adminPhoto;
    }
    
    public void setAdminPhoto(byte[] adminPhoto) {
        this.adminPhoto = adminPhoto;
    }
}


