package com.advertisement.entity;
// Generated Apr 26, 2017 12:47:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="area"
    ,catalog="advertise"
)
public class Area  implements java.io.Serializable {


     private Integer areaId;
     private District district;
     private String areaName;
     private Set<OtherAdvertise> otherAdvertises = new HashSet<OtherAdvertise>(0);
     private Set<HouseAdvertise> houseAdvertises = new HashSet<HouseAdvertise>(0);
     private Set<User> users = new HashSet<User>(0);

    public Area() {
    }

	
    public Area(District district, String areaName) {
        this.district = district;
        this.areaName = areaName;
    }
    public Area(District district, String areaName, Set<OtherAdvertise> otherAdvertises, Set<HouseAdvertise> houseAdvertises, Set<User> users) {
       this.district = district;
       this.areaName = areaName;
       this.otherAdvertises = otherAdvertises;
       this.houseAdvertises = houseAdvertises;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="area_id", unique=true, nullable=false)
    public Integer getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="district_id", nullable=false)
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }

    
    @Column(name="area_name", nullable=false, length=300)
    public String getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set<OtherAdvertise> getOtherAdvertises() {
        return this.otherAdvertises;
    }
    
    public void setOtherAdvertises(Set<OtherAdvertise> otherAdvertises) {
        this.otherAdvertises = otherAdvertises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set<HouseAdvertise> getHouseAdvertises() {
        return this.houseAdvertises;
    }
    
    public void setHouseAdvertises(Set<HouseAdvertise> houseAdvertises) {
        this.houseAdvertises = houseAdvertises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


