package com.advertisement.entity;
// Generated Apr 26, 2017 12:47:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CarAdvertise generated by hbm2java
 */
@Entity
@Table(name="car_advertise"
    ,catalog="advertise"
)
public class CarAdvertise  implements java.io.Serializable {


     private Integer carId;
     private District district;
     private Division division;
     private User user;
     private String carType;
     private String carModel;
     private double rentPerDay;
     private byte[] carImage;
     private String advertisementTitle;
     private String carDescription;
     private Date postDate;
     private char status;
     private Set<CarComment> carComments = new HashSet<CarComment>(0);

    public CarAdvertise() {
    }

	
    public CarAdvertise(District district, Division division, User user, String carType, double rentPerDay, Date postDate, char status) {
        this.district = district;
        this.division = division;
        this.user = user;
        this.carType = carType;
        this.rentPerDay = rentPerDay;
        this.postDate = postDate;
        this.status = status;
    }
    public CarAdvertise(District district, Division division, User user, String carType, String carModel, double rentPerDay, byte[] carImage, String advertisementTitle, String carDescription, Date postDate, char status, Set<CarComment> carComments) {
       this.district = district;
       this.division = division;
       this.user = user;
       this.carType = carType;
       this.carModel = carModel;
       this.rentPerDay = rentPerDay;
       this.carImage = carImage;
       this.advertisementTitle = advertisementTitle;
       this.carDescription = carDescription;
       this.postDate = postDate;
       this.status = status;
       this.carComments = carComments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="car_id", unique=true, nullable=false)
    public Integer getCarId() {
        return this.carId;
    }
    
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="district_id", nullable=false)
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="division_id", nullable=false)
    public Division getDivision() {
        return this.division;
    }
    
    public void setDivision(Division division) {
        this.division = division;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="car_type", nullable=false, length=100)
    public String getCarType() {
        return this.carType;
    }
    
    public void setCarType(String carType) {
        this.carType = carType;
    }

    
    @Column(name="car_model", length=100)
    public String getCarModel() {
        return this.carModel;
    }
    
    public void setCarModel(String carModel) {
        this.carModel = carModel;
    }

    
    @Column(name="rent_per_day", nullable=false, precision=22, scale=0)
    public double getRentPerDay() {
        return this.rentPerDay;
    }
    
    public void setRentPerDay(double rentPerDay) {
        this.rentPerDay = rentPerDay;
    }

    
    @Column(name="car_image")
    public byte[] getCarImage() {
        return this.carImage;
    }
    
    public void setCarImage(byte[] carImage) {
        this.carImage = carImage;
    }

    
    @Column(name="advertisement_title", length=100)
    public String getAdvertisementTitle() {
        return this.advertisementTitle;
    }
    
    public void setAdvertisementTitle(String advertisementTitle) {
        this.advertisementTitle = advertisementTitle;
    }

    
    @Column(name="car_description", length=350)
    public String getCarDescription() {
        return this.carDescription;
    }
    
    public void setCarDescription(String carDescription) {
        this.carDescription = carDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="post_date", nullable=false, length=19)
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    
    @Column(name="status", nullable=false, length=1)
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="carAdvertise")
    public Set<CarComment> getCarComments() {
        return this.carComments;
    }
    
    public void setCarComments(Set<CarComment> carComments) {
        this.carComments = carComments;
    }




}


