package com.advertisement.entity;
// Generated Apr 26, 2017 12:47:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CarComment generated by hbm2java
 */
@Entity
@Table(name="car_comment"
    ,catalog="advertise"
)
public class CarComment  implements java.io.Serializable {


     private Integer carCommentId;
     private CarAdvertise carAdvertise;
     private User user;
     private String comments;

    public CarComment() {
    }

	
    public CarComment(CarAdvertise carAdvertise, User user) {
        this.carAdvertise = carAdvertise;
        this.user = user;
    }
    public CarComment(CarAdvertise carAdvertise, User user, String comments) {
       this.carAdvertise = carAdvertise;
       this.user = user;
       this.comments = comments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="car_comment_id", unique=true, nullable=false)
    public Integer getCarCommentId() {
        return this.carCommentId;
    }
    
    public void setCarCommentId(Integer carCommentId) {
        this.carCommentId = carCommentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="car_id", nullable=false)
    public CarAdvertise getCarAdvertise() {
        return this.carAdvertise;
    }
    
    public void setCarAdvertise(CarAdvertise carAdvertise) {
        this.carAdvertise = carAdvertise;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="comments", length=450)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


