package com.advertisement.entity;
// Generated Apr 26, 2017 12:47:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HouseComment generated by hbm2java
 */
@Entity
@Table(name="house_comment"
    ,catalog="advertise"
)
public class HouseComment  implements java.io.Serializable {


     private Integer houseCommentId;
     private HouseAdvertise houseAdvertise;
     private User user;

    public HouseComment() {
    }

    public HouseComment(HouseAdvertise houseAdvertise, User user) {
       this.houseAdvertise = houseAdvertise;
       this.user = user;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="house_comment_id", unique=true, nullable=false)
    public Integer getHouseCommentId() {
        return this.houseCommentId;
    }
    
    public void setHouseCommentId(Integer houseCommentId) {
        this.houseCommentId = houseCommentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="house_id", nullable=false)
    public HouseAdvertise getHouseAdvertise() {
        return this.houseAdvertise;
    }
    
    public void setHouseAdvertise(HouseAdvertise houseAdvertise) {
        this.houseAdvertise = houseAdvertise;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


