package com.advertisement.entity;
// Generated Apr 26, 2017 12:47:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HouseAdvertise generated by hbm2java
 */
@Entity
@Table(name="house_advertise"
    ,catalog="advertise"
)
public class HouseAdvertise  implements java.io.Serializable {


     private Integer houseId;
     private Area area;
     private District district;
     private Division division;
     private User user;
     private String nearTo;
     private String houseAddress;
     private int bedNo;
     private Integer bathNo;
     private Double houseSize;
     private byte[] houseImg;
     private Double houseRent;
     private String advertisementTitle;
     private String description;
     private String contactNo;
     private Date postDate;
     private Date applicableFrom;
     private char status;
     private Set<HouseComment> houseComments = new HashSet<HouseComment>(0);

    public HouseAdvertise() {
    }

	
    public HouseAdvertise(Area area, District district, Division division, User user, String nearTo, String houseAddress, int bedNo, Date postDate, char status) {
        this.area = area;
        this.district = district;
        this.division = division;
        this.user = user;
        this.nearTo = nearTo;
        this.houseAddress = houseAddress;
        this.bedNo = bedNo;
        this.postDate = postDate;
        this.status = status;
    }
    public HouseAdvertise(Area area, District district, Division division, User user, String nearTo, String houseAddress, int bedNo, Integer bathNo, Double houseSize, byte[] houseImg, Double houseRent, String advertisementTitle, String description, String contactNo, Date postDate, Date applicableFrom, char status, Set<HouseComment> houseComments) {
       this.area = area;
       this.district = district;
       this.division = division;
       this.user = user;
       this.nearTo = nearTo;
       this.houseAddress = houseAddress;
       this.bedNo = bedNo;
       this.bathNo = bathNo;
       this.houseSize = houseSize;
       this.houseImg = houseImg;
       this.houseRent = houseRent;
       this.advertisementTitle = advertisementTitle;
       this.description = description;
       this.contactNo = contactNo;
       this.postDate = postDate;
       this.applicableFrom = applicableFrom;
       this.status = status;
       this.houseComments = houseComments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="house_id", unique=true, nullable=false)
    public Integer getHouseId() {
        return this.houseId;
    }
    
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="area_id", nullable=false)
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="district_id", nullable=false)
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="division_id", nullable=false)
    public Division getDivision() {
        return this.division;
    }
    
    public void setDivision(Division division) {
        this.division = division;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="near_to", nullable=false, length=200)
    public String getNearTo() {
        return this.nearTo;
    }
    
    public void setNearTo(String nearTo) {
        this.nearTo = nearTo;
    }

    
    @Column(name="house_address", nullable=false, length=300)
    public String getHouseAddress() {
        return this.houseAddress;
    }
    
    public void setHouseAddress(String houseAddress) {
        this.houseAddress = houseAddress;
    }

    
    @Column(name="bed_no", nullable=false)
    public int getBedNo() {
        return this.bedNo;
    }
    
    public void setBedNo(int bedNo) {
        this.bedNo = bedNo;
    }

    
    @Column(name="bath_no")
    public Integer getBathNo() {
        return this.bathNo;
    }
    
    public void setBathNo(Integer bathNo) {
        this.bathNo = bathNo;
    }

    
    @Column(name="house_size", precision=22, scale=0)
    public Double getHouseSize() {
        return this.houseSize;
    }
    
    public void setHouseSize(Double houseSize) {
        this.houseSize = houseSize;
    }

    
    @Column(name="house_img")
    public byte[] getHouseImg() {
        return this.houseImg;
    }
    
    public void setHouseImg(byte[] houseImg) {
        this.houseImg = houseImg;
    }

    
    @Column(name="house_rent", precision=22, scale=0)
    public Double getHouseRent() {
        return this.houseRent;
    }
    
    public void setHouseRent(Double houseRent) {
        this.houseRent = houseRent;
    }

    
    @Column(name="advertisement_title", length=100)
    public String getAdvertisementTitle() {
        return this.advertisementTitle;
    }
    
    public void setAdvertisementTitle(String advertisementTitle) {
        this.advertisementTitle = advertisementTitle;
    }

    
    @Column(name="description", length=450)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="contact_no", length=45)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="post_date", nullable=false, length=19)
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="applicable_from", length=10)
    public Date getApplicableFrom() {
        return this.applicableFrom;
    }
    
    public void setApplicableFrom(Date applicableFrom) {
        this.applicableFrom = applicableFrom;
    }

    
    @Column(name="status", nullable=false, length=1)
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="houseAdvertise")
    public Set<HouseComment> getHouseComments() {
        return this.houseComments;
    }
    
    public void setHouseComments(Set<HouseComment> houseComments) {
        this.houseComments = houseComments;
    }




}


