package com.advertisement.entity;
// Generated Apr 26, 2017 12:47:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OtherComment generated by hbm2java
 */
@Entity
@Table(name="other_comment"
    ,catalog="advertise"
)
public class OtherComment  implements java.io.Serializable {


     private Integer otherCommentId;
     private OtherAdvertise otherAdvertise;
     private User user;
     private String comments;

    public OtherComment() {
    }

	
    public OtherComment(OtherAdvertise otherAdvertise, User user) {
        this.otherAdvertise = otherAdvertise;
        this.user = user;
    }
    public OtherComment(OtherAdvertise otherAdvertise, User user, String comments) {
       this.otherAdvertise = otherAdvertise;
       this.user = user;
       this.comments = comments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="other_comment_id", unique=true, nullable=false)
    public Integer getOtherCommentId() {
        return this.otherCommentId;
    }
    
    public void setOtherCommentId(Integer otherCommentId) {
        this.otherCommentId = otherCommentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="other_post_id", nullable=false)
    public OtherAdvertise getOtherAdvertise() {
        return this.otherAdvertise;
    }
    
    public void setOtherAdvertise(OtherAdvertise otherAdvertise) {
        this.otherAdvertise = otherAdvertise;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="comments", length=450)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


